### PR TITLE
Aspirational lints

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**
These are lints I'd like the codebase to one day pass. I expect they don't pass now. Mostly stolen from Interchange.

### CODE REVIEW

**Comment by mattwthompson** [comment]
This is super duper in my wheelhouse; if you'd like feedback at any point I'm happy to oblige

**Comment by Yoshanuikabundi** [comment]
Thanks Matt, will let you know - I just saw the trailing commas pre-commit on Interchange and was like "I WANT THAT" :laughing: 

If you have feedback in mind I obvs want to hear it but I'm assuming you know that and are offering a more formal review at some point, in which case I appreciate it and will let you know :grin:

**Comment by mattwthompson** [comment]
Hot dang, I did some stuff and it worked

**Comment by Yoshanuikabundi** [comment]
Holy crap go @mattwthompson!

Are there any change or commits or files that have been manually edited, or is this all automatic changes from lints? It looks amazing! I guess you dropped interrogate coz we're a long way off being full of docstrings?

**Comment by mattwthompson** [comment]
Some of the documentation changes in [26d9f53](https://github.com/openforcefield/openff-bespokefit/pull/264/commits/26d9f53f6c2c706a0b1237894a31ba1e0222d833) are manual, but I tried to make no or minimal changes to the source code. I think my likely errors here, if any, or the sort of things to look out if it were possible to review this, are inaccurate statements in some docstrings. Given that (to my surprise) tests are passing I think the chances I broke something are low; adding a type checker is arguably a better way to review this than reading so many LOC.

> I guess you dropped interrogate coz we're a long way off being full of docstrings?

I dropped it because I forgot why I had it in Interchange in the first place. We could add it back in and see what happens - `pydocstyle` complains when anything public lacks a docstring, so I bet the coverage is actually quite good.

**Comment by mattwthompson** [comment]
This was fun to work on but it doesn't seem valued - if anybody wishes to pick this up, I'm leaving the branch dangling on the remote

**Pull request closed without merging**
