### PR TITLE
Avoid RDKit 2024.03.4

### PR DESCRIPTION
**Pull request by mattwthompson**

### CODE REVIEW

**Comment by mattwthompson** [comment]
These failures might be legit, I can't tell. The traceback is just kinda a crash

**Comment by mattwthompson** [comment]
I don't know where to start diagnosing this
```
Run python -m pytest -v --cov=openff --cov-config=setup.cfg openff/bespokefit/_tests/ --cov-report=xml
  python -m pytest -v --cov=openff --cov-config=setup.cfg openff/bespokefit/_tests/ --cov-report=xml
  shell: /bin/bash -l {0}
  env:
    OE_LICENSE: /Users/runner/work/openff-bespokefit/openff-bespokefit/oe_license.txt
    MAMBA_ROOT_PREFIX: /Users/runner/micromamba
    MAMBA_EXE: /Users/runner/micromamba-bin/micromamba
    CONDARC: /Users/runner/work/_temp/setup-micromamba/.condarc
============================= test session starts ==============================
platform darwin -- Python 3.10.14, pytest-7.4.4, pluggy-1.5.0 -- /Users/runner/micromamba/envs/bespokefit-no-openeye/bin/python
cachedir: .pytest_cache
rootdir: /Users/runner/work/openff-bespokefit/openff-bespokefit
configfile: setup.cfg
plugins: celery-0.0.0a1, cov-5.0.0, asyncio-0.[2](https://github.com/openforcefield/openff-bespokefit/actions/runs/9942012289/job/27464904653?pr=353#step:8:2)3.7, anyio-4.4.0, requests-mock-1.12.1
asyncio: mode=strict
collecting ... collected 382 items

openff/bespokefit/_tests/cli/test_cache.py::test_results_from_file[torsiondrive] PASSED [  0%]
openff/bespokefit/_tests/cli/test_cache.py::test_results_from_file[optimization] PASSED [  0%]
openff/bespokefit/_tests/cli/test_cache.py::test_results_from_file[hessian] PASSED [  0%]
openff/bespokefit/_tests/cli/test_cache.py::test_connecting_to_fractal_address[QCArchive] PASSED [  1%]
Error: bespokefit/_tests/cli/test_cache.py::test_connecting_to_fractal_address[Error] PASSED [  1%]
openff/bespokefit/_tests/cli/test_cache.py::test_connecting_to_fractal_file PASSED [  1%]
openff/bespokefit/_tests/cli/test_cache.py::test_update_from_qcsubmit PASSED [  1%]
openff/bespokefit/_tests/cli/test_cache.py::test_cache_cli_fractal PASSED [  2%]
openff/bespokefit/_tests/cli/test_combine.py::test_combine_no_args PASSED [  2%]
openff/bespokefit/_tests/cli/test_combine.py::test_combine_local_and_tasks PASSED [  2%]
openff/bespokefit/_tests/cli/test_prepare.py::test_prepare_errors[abc-openff-1.[3](https://github.com/openforcefield/openff-bespokefit/actions/runs/9942012289/job/27464904653?pr=353#step:8:3).0.offxml-the input path did not point to a valid optimization] PASSED [  2%]
openff/bespokefit/_tests/cli/test_prepare.py::test_prepare_errors[-fake-ff-path.offxml2-error loading initial parameters] PASSED [  3%]
openff/bespokefit/_tests/cli/test_prepare.py::test_prepare PASSED        [  3%]
openff/bespokefit/_tests/cli/test_utilities.py::test_print_header PASSED [  3%]
openff/bespokefit/_tests/cli/test_utilities.py::test_create_command PASSED [  3%]
openff/bespokefit/_tests/cli/test_utilities.py::test_exit_with_messages PASSED [  [4](https://github.com/openforcefield/openff-bespokefit/actions/runs/9942012289/job/27464904653?pr=353#step:8:4)%]
openff/bespokefit/_tests/cli/test_worker.py::test_launch_worker[fragmenter] PASSED [  4%]
openff/bespokefit/_tests/cli/test_worker.py::test_launch_worker[qc-compute] PASSED [  4%]
openff/bespokefit/_tests/cli/test_worker.py::test_launch_worker[optimizer] PASSED [  4%]
openff/bespokefit/_tests/cli/executor/test_launch.py::test_launch PASSED [  [5](https://github.com/openforcefield/openff-bespokefit/actions/runs/9942012289/job/27464904653?pr=353#step:8:5)%]
openff/bespokefit/_tests/cli/executor/test_launch.py::test_validate_redis_connection_exists PASSED [  5%]
openff/bespokefit/_tests/cli/executor/test_launch.py::test_validate_redis_connection_config PASSED [  5%]
openff/bespokefit/_tests/cli/executor/test_list.py::test_get_columns PASSED [  [6](https://github.com/openforcefield/openff-bespokefit/actions/runs/9942012289/job/27464904653?pr=353#step:8:6)%]
openff/bespokefit/_tests/cli/executor/test_list.py::test_list_cli[0-No optimizations were found] PASSED [  6%]
openff/bespokefit/_tests/cli/executor/test_list.py::test_list_cli[3-The following optimizations were found] PASSED [  6%]
openff/bespokefit/_tests/cli/executor/test_retrieve.py::test_retrieve_one_output PASSED [  6%]
openff/bespokefit/_tests/cli/executor/test_retrieve.py::test_retrieve_output[waiting-the bespoke fit is queued] PASSED [  [7](https://github.com/openforcefield/openff-bespokefit/actions/runs/9942012289/job/27464904653?pr=353#step:8:7)%]
openff/bespokefit/_tests/cli/executor/test_retrieve.py::test_retrieve_output[running-the bespoke fit is running] PASSED [  7%]
openff/bespokefit/_tests/cli/executor/test_retrieve.py::test_retrieve_output[errored-the bespoke fit is errored] PASSED [  7%]
openff/bespokefit/_tests/cli/executor/test_retrieve.py::test_retrieve_output[success-the bespoke fit is finished] PASSED [  7%]
openff/bespokefit/_tests/cli/executor/test_retrieve.py::test_retrieve_force_field[running-the bespoke fit is still running and so no force field-False] PASSED [  [8](https://github.com/openforcefield/openff-bespokefit/actions/runs/9942012289/job/27464904653?pr=353#step:8:8)%]
openff/bespokefit/_tests/cli/executor/test_retrieve.py::test_retrieve_force_field[errored-the bespoke fit failed and so no force field-False] PASSED [  8%]
openff/bespokefit/_tests/executor/services/test_models.py::test_link_comparison[link_a2-eq-link_b2-True] PASSED [ 21%]
openff/bespokefit/_tests/executor/services/test_models.py::test_link_comparison[link_a3-eq-link_b3-False] PASSED [ 21%]
openff/bespokefit/_tests/executor/services/test_models.py::test_link_comparison[link_a4-ne-link_b4-False] PASSED [ 22%]
openff/bespokefit/_tests/executor/services/test_models.py::test_link_comparison[link_a5-ne-link_b5-True] PASSED [ 22%]
openff/bespokefit/_tests/executor/services/test_models.py::test_link_hash PASSED [ 22%]
openff/bespokefit/_tests/executor/services/test_settings.py::TestSettings::test_fragmenter_settings PASSED [ 23%]
openff/bespokefit/_tests/executor/services/test_settings.py::TestSettings::test_qc_compute_settings PASSED [ 23%]
openff/bespokefit/_tests/executor/services/test_settings.py::TestSettings::test_optimizer_settings PASSED [ 23%]
openff/bespokefit/_tests/executor/services/test_settings.py::TestSettings::test_apply_env PASSED [ 23%]
openff/bespokefit/_tests/executor/services/test_stages.py::test_generate_torsions PASSED [ 24%]
openff/bespokefit/_tests/executor/services/test_stages.py::test_generate_parameters PASSED [ 24%]
openff/bespokefit/_tests/executor/services/test_stages.py::test_generate_parameters_multiple_stages PASSED [ 24%]
openff/bespokefit/_tests/executor/services/coordinator/test_app.py::test_get_optimizations[0-3-None-expected_ids0-None-None] PASSED [ 24%]
openff/bespokefit/_tests/executor/services/coordinator/test_app.py::test_get_optimizations[0-2-None-expected_ids1-None-/api/v1/tasks?skip=2&limit=2] PASSED [ 25%]
openff/bespokefit/_tests/executor/services/coordinator/test_app.py::test_get_optimizations[1-1-None-expected_ids2-/api/v1/tasks?skip=0&limit=1-/api/v1/tasks?skip=2&limit=1] PASSED [ 25%]
openff/bespokefit/_tests/executor/services/coordinator/test_app.py::test_get_optimizations[1-1-waiting-expected_ids3-/api/v1/tasks?skip=0&limit=1&status=waiting-None] PASSED [ 25%]
openff/bespokefit/_tests/executor/services/coordinator/test_app.py::test_get_optimizations[0-1-complete-expected_ids4-None-None] PASSED [ 25%]
openff/bespokefit/_tests/executor/services/coordinator/test_app.py::test_get_optimization PASSED [ 26%]
openff/bespokefit/_tests/executor/services/coordinator/test_app.py::test_post_optimization PASSED [ 26%]
openff/bespokefit/_tests/executor/services/coordinator/test_app.py::test_post_optimization_error PASSED [ 26%]
openff/bespokefit/_tests/executor/services/coordinator/test_app.py::test_get_molecule_image PASSED [ 26%]
openff/bespokefit/_tests/executor/services/coordinator/test_models.py::test_get_status_from_stage[stage0-expected0] PASSED [ 27%]
openff/bespokefit/_tests/executor/services/coordinator/test_models.py::test_get_status_from_stage[stage1-expected1] PASSED [ 27%]
openff/bespokefit/_tests/executor/services/coordinator/test_models.py::test_get_status_from_stage[stage2-expected2] PASSED [ 27%]
openff/bespokefit/_tests/executor/services/coordinator/test_models.py::test_get_from_task[task0-expected0] PASSED [ 28%]
openff/bespokefit/_tests/executor/services/coordinator/test_models.py::test_get_from_task[task1-expected1] PASSED [ 28%]
openff/bespokefit/_tests/executor/services/coordinator/test_models.py::test_get_from_task[task2-expected2] PASSED [ 28%]
openff/bespokefit/_tests/executor/services/coordinator/test_models.py::test_task_status[task0-waiting] PASSED [ 28%]
openff/bespokefit/_tests/executor/services/coordinator/test_models.py::test_task_status[task1-running] PASSED [ 2[9](https://github.com/openforcefield/openff-bespokefit/actions/runs/9942012289/job/27464904653?pr=353#step:8:10)%]
openff/bespokefit/_tests/executor/services/coordinator/test_models.py::test_task_status[task2-success] PASSED [ 29%]
openff/bespokefit/_tests/executor/services/coordinator/test_models.py::test_task_status[task3-errored] PASSED [ 29%]
openff/bespokefit/_tests/executor/services/coordinator/test_models.py::test_task_status[task4-running] PASSED [ 29%]
openff/bespokefit/_tests/executor/services/coordinator/test_storage.py::test_task_id_to_key PASSED [ 30%]
openff/bespokefit/_tests/executor/services/coordinator/test_storage.py::test_get_task PASSED [ 30%]
openff/bespokefit/_tests/executor/services/coordinator/test_storage.py::test_get_task_ids[0-3-expected_ids0-None] PASSED [ 30%]
openff/bespokefit/_tests/executor/services/coordinator/test_storage.py::test_get_task_ids[0-3-expected_ids1-status1] PASSED [ 30%]
openff/bespokefit/_tests/executor/services/coordinator/test_storage.py::test_get_task_ids[0-2-expected_ids2-None] PASSED [ 31%]
openff/bespokefit/_tests/executor/services/coordinator/test_storage.py::test_get_task_ids[1-1-expected_ids3-None] PASSED [ 31%]
openff/bespokefit/_tests/executor/services/coordinator/test_storage.py::test_get_task_ids[0-3-expected_ids4-status4] PASSED [ 31%]
openff/bespokefit/_tests/executor/services/coordinator/test_storage.py::test_get_task_ids[0-3-expected_ids5-status5] PASSED [ 31%]
openff/bespokefit/_tests/executor/services/coordinator/test_storage.py::test_get_task_ids[1-1-expected_ids6-status6] PASSED [ 32%]
openff/bespokefit/_tests/executor/services/coordinator/test_storage.py::test_create_task PASSED [ 32%]
openff/bespokefit/_tests/executor/services/coordinator/test_storage.py::test_peek_pop_push_task_state PASSED [ 32%]
openff/bespokefit/_tests/executor/services/coordinator/test_storage.py::test_save_task PASSED [ 32%]
openff/bespokefit/_tests/executor/services/coordinator/test_utils.py::test_hash_fitting_schema PASSED [ 33%]
openff/bespokefit/_tests/executor/services/coordinator/test_utils.py::test_get_cached_parameters PASSED [ 33%]
openff/bespokefit/_tests/executor/services/coordinator/test_utils.py::test_cache_parameters PASSED [ 33%]
openff/bespokefit/_tests/executor/services/coordinator/test_workers.py::test_process_task PASSED [ 34%]
openff/bespokefit/_tests/executor/services/fragmenter/test_app.py::test_get_fragment PASSED [ 34%]
openff/bespokefit/_tests/executor/services/fragmenter/test_app.py::test_post_fragment PASSED [ 34%]
openff/bespokefit/_tests/executor/services/fragmenter/test_app.py::test_get_molecule_image PASSED [ 34%]
openff/bespokefit/_tests/executor/services/fragmenter/test_app.py::test_get_molecule_image_pending PASSED [ 35%]
openff/bespokefit/_tests/executor/services/fragmenter/test_app.py::test_get_molecule_image_bad_id PASSED [ 35%]
openff/bespokefit/_tests/executor/services/fragmenter/test_cache.py::test_cached_fragmentation_task PASSED [ 35%]
openff/bespokefit/_tests/executor/services/fragmenter/test_worker.py::test_fragment PASSED [ 35%]
/Users/runner/work/_temp/bdd7c668-fa1e-494d-a834-798245574c48.sh: line 1:  33[13](https://github.com/openforcefield/openff-bespokefit/actions/runs/9942012289/job/27464904653?pr=353#step:8:14) Trace/BPT trap: 5       python -m pytest -v --cov=openff --cov-config=setup.cfg openff/bespokefit/_tests/ --cov-report=xml
openff/bespokefit/_tests/executor/services/fragmenter/test_worker.py::test_fragment_mock 
Error: Process completed with exit code 133.
```

**Comment by j-wags** [comment]
Hm, big day for CI. I'll look into this and report if I find anything.

**Comment by mattwthompson** [comment]
Upstream is fixed, CI is not

**Comment by mattwthompson** [comment]
The problem is actually with RDKit https://github.com/openforcefield/openff-bespokefit/issues/354

**Comment by mattwthompson** [comment]
The problems are upstream without a concrete timeline for resolution. I need to merge this to get tests passing

**Pull request merged**
