### PR TITLE
Add `.pre-commit-config.yaml`

### PR DESCRIPTION
**Pull request by mattwthompson**
## Description
This PR sets up `pre-commit` for this repo [as requested](https://github.com/openforcefield/openff-bespokefit/pull/225#pullrequestreview-1300817188).

This duplicates the linting action, but not exactly, and I personally prefer removing it altogether to avoid confusing states in the future.

~~I intentionally based this off of `main` to avoid the branch dependency; coordinating it with #225 won't be hard.~~ Everything's in sync now.

I left out many hooks I like; this pretty closely matches what is already done. We can of course add others later if desired.

I left out all notebook hooks since this repo doesn't have any. If it ever does, I've been really happy with the features of nbQA and the maintenance by its main author.

The CI service, which I enabled and will run on PRs if this is merged in, offers an auto-update feature that automatically updates hooks - i.e. a new version of a tool is released - and runs them on the codebase. The default frequency is weekly but this can be [configured](https://pre-commit.ci/#configuration) to others

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [x] Set up `pre-commit`
  - [x] Enable `pre-commit.ci`

## Questions
- [ ] Remove linting workflow?

## Status
- [x] Ready to go

### CODE REVIEW

**Review by Yoshanuikabundi — APPROVED** [review]
Thanks @mattwthompson, this is fantastic. Could you shoot me a reminder of how to install the pre-commit hooks locally so I can add it to the Readme?

**Comment by mattwthompson** [comment]
`pip install pre-commit` or `mamba install pre-commit -c conda-forge`, after which I like to throw a `pre-commit run --all-files`, which handles installing the hooks prior to running them

**Comment by Yoshanuikabundi** [comment]
Oh and I forgot to mention in my review - I agree that we should remove the lint CI action and just rely on the pre-commit :) If you wanna do that in this PR that'd be great, otherwise I can do it!

**Comment by jthorton** [comment]
Can we add the pre-commit badges to the README as well?

**Review by Yoshanuikabundi — APPROVED** [review]
Awesome! Thanks @mattwthompson!!

**Comment by Yoshanuikabundi** [comment]
Hey @mattwthompson is there something holding this up? It's blocking testing on a number of other PRs so I think I'll merge it myself tomorrow if I don't hear back :)

**Comment by mattwthompson** [comment]
I wasn't sure if you wanted green check marks before merging - I'll fire it off now

**Comment by mattwthompson** [comment]
Deployment seems fine; it's already installed as an app and the merge commit [ran all checks ](https://results.pre-commit.ci/run/github/241694600/1679365594.ms6eUS0GQWi1-mojqKAh0w)in 6.1 seconds (!)

**Comment by Yoshanuikabundi** [comment]
Ah sorry Matt I'll try to be clearer in future - the red check marks are from other PRs that are about to be merged. This is awesome, thanks!!

**Pull request merged**
