### PR TITLE
Add h5py shim in installation docs

### PR DESCRIPTION
**Pull request by mattwthompson**
## Description
A soft safeguard against #227

## Todos
Notable points that this PR has either accomplished or will accomplish.
 - [x] Add `"h5py>=3.6" constraint in Psi4 one-liners; this probably would have prevented the linked issue from being raised.

## Questions
- [ ] Question1

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by Yoshanuikabundi** [comment]
72fdce2 looks great, but this PR still has a whole bunch of other commits from the 0.2 branch - could you rebase it or cherry pick it so it's just those changes?

**Comment by mattwthompson** [comment]
Whoops, didn't see I started it off of the wrong branch. Should be fixed now.

**Review by jthorton — APPROVED** [review]

**Review by Yoshanuikabundi — APPROVED** [review]
LGTM!

**Comment by mattwthompson** [comment]
This should maybe also be ported onto `main`, I have not checked what's there

**Pull request merged**
