### PR TITLE
Switch to `setup-micromamba`

### PR DESCRIPTION
**Pull request by mattwthompson**
## Description
Provide a brief description of the PR's purpose here.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [ ] TODO 1

## Questions
- [ ] Question1

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by mattwthompson** [comment]
I have no clue why the OpenEye license isn't found

I opened https://github.com/openforcefield/openff-bespokefit/pull/266 which probably doesn't fix that but still might be useful

**Comment by mattwthompson** [comment]
I think this should be good to go after merging #266 in

**Comment by Yoshanuikabundi** [comment]
Sorry, looks like I had my PR notifications off! This looks great to me, thanks Matt. Is it good to go?

**Comment by mattwthompson** [comment]
Yup - should be good to go, thanks

**Review by Yoshanuikabundi — APPROVED** [review]
Perfect!

**Pull request merged**
